apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: feedback-form
  namespace: deep-dive-quarkus
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
spec:
  host: feedback-form.apps.ocp4.klaassen.click
  to:
    kind: Service
    name: feedback-form
  tls:
    termination: "edge"
---
kind: Secret
apiVersion: v1
metadata:
  name: mariadb-config
  namespace: deep-dive-quarkus
stringData:
  user: maria
  userPassword: password
  host: mariadb.deep-dive-quarkus.svc.cluster.local:3306
  database: feedback
  rootPassword: root
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  namespace: deep-dive-quarkus
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: registry.redhat.io/rhel9/mariadb-105
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mariadb-config
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: userPassword
              name: mariadb-config
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database
              name: mariadb-config
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rootPassword
              name: mariadb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: deep-dive-quarkus
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
